// DSFH IM Residency Portal — Edge Function: ical
//
// Generates a live RFC-5545 iCalendar (.ics) feed for a specific user.
// Calendar apps (Apple Calendar, Google Calendar, Outlook) subscribe to this
// URL and auto-refresh it periodically — events appear automatically as
// rotations, on-call shifts, meetings, and deadlines are assigned.
//
// Usage:  GET /functions/v1/ical?token=<calendar_token>
// Returns: text/calendar (.ics)
//
// The token is stored in profiles.calendar_token (a UUID generated by the
// portal UI).  No authentication is required — the token IS the credential.
// Revoking access = regenerating the token in the portal.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// Block start dates — DD/MM format, academic year Oct–Sep
// Month < 9 means the date falls in academicYear+1 (i.e. the spring/summer half)
const ROTA_PERIODS = [
  "28/9-25/10","26/10-22/11","23/11-20/12","21/12-17/1",
  "18/1-14/2","15/2-14/3","15/3-11/4","12/4-9/5",
  "10/5-6/6","7/6-4/7","5/7-1/8","2/8-29/8","30/8-26/9",
];

function blockStartDate(blockNum: number, academicYear: number): Date {
  const period = ROTA_PERIODS[blockNum - 1];
  if (!period) return new Date(0);
  const startStr = period.split("-")[0];
  const [sdStr, smStr] = startStr.split("/");
  const sd = parseInt(sdStr, 10);
  const sm = parseInt(smStr, 10);
  const year = sm >= 9 ? academicYear : academicYear + 1;
  return new Date(Date.UTC(year, sm - 1, sd));
}

function currentAcademicYear(): number {
  const now = new Date();
  const m = now.getMonth(); // 0-indexed; 9 = October
  return m >= 9 ? now.getFullYear() : now.getFullYear() - 1;
}

function icsDate(d: Date): string {
  return d.toISOString().split("T")[0].replace(/-/g, "");
}

function icsEscape(s: string): string {
  return (s || "")
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

// RFC 5545 §3.1: fold lines longer than 75 octets
function fold(line: string): string {
  if (line.length <= 75) return line;
  const parts: string[] = [];
  while (line.length > 75) {
    parts.push(line.slice(0, 75));
    line = " " + line.slice(75);
  }
  parts.push(line);
  return parts.join("\r\n");
}

const SLOT_LABELS: Record<string, string> = {
  er_medical: "ER Medical Oncall", bldg1: "Floor Oncall", bldg2: "Floor Oncall",
  consult: "Floor Oncall", ctu1: "CTU Cover A", ctu2: "CTU Cover B",
};

// Mirrors the client's isWeekendDate()/oncallHoursLabel() (SFH_Residency_Portal.html)
// — CTU day-cover is always 08:00-16:00; other slots are 08:00-22:00 on Fri/Sat
// (weekend) and 16:00-22:00 on weekdays. Must stay in sync with the client logic.
function isWeekendDate(ds: string): boolean {
  const [y, m, d] = ds.split("-").map(Number);
  return [5, 6].includes(new Date(Date.UTC(y, m - 1, d)).getUTCDay());
}
function slotTimes(slotKey: string, ds: string): [string, string] {
  if (slotKey === "ctu1" || slotKey === "ctu2") return ["080000", "160000"];
  return isWeekendDate(ds) ? ["080000", "220000"] : ["160000", "220000"];
}

const ANN_ICON: Record<string, string> = {
  task: "📋", research: "🔬", qi: "📈",
  presentation: "🎤", deadline: "⏰", other: "📌",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: CORS_HEADERS });
  }

  const url = new URL(req.url);
  const token = url.searchParams.get("token");

  if (!token) {
    return new Response("Missing calendar token.", {
      status: 400,
      headers: { "Content-Type": "text/plain" },
    });
  }

  const sb = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  // Identify user by their calendar token
  const { data: profile, error: profErr } = await sb
    .from("profiles")
    .select("id, display_name, role, resident_id, calendar_prefs")
    .eq("calendar_token", token)
    .single();

  if (profErr || !profile) {
    return new Response("Invalid or expired calendar token.", {
      status: 401,
      headers: { "Content-Type": "text/plain" },
    });
  }

  // ── Apple Configuration Profile (.mobileconfig) ────────────────────────────
  // Installs the feed as a native Subscribed Calendar account via iOS's own
  // profile installer. This downloads over plain https (a normal Safari file
  // download, not a webcal:// scheme handoff), so it never hits the iOS bug
  // where webcal:// links get silently downgraded to http:// and fail
  // validation. The https server/path/port are embedded directly in the
  // profile, so Calendar always connects securely.
  if (url.searchParams.get("format") === "mobileconfig") {
    const host = url.hostname;
    const path = "/functions/v1/ical?token=" + token;
    const name = (profile.display_name || "Resident").replace(/^Dr\.?\s*/i, "").trim();
    const xmlEscape = (s: string) =>
      s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const payloadUuid = crypto.randomUUID();
    const profileUuid = crypto.randomUUID();
    const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>PayloadContent</key>
  <array>
    <dict>
      <key>PayloadDescription</key>
      <string>Subscribes to the DSFH IM Residency live calendar feed.</string>
      <key>PayloadDisplayName</key>
      <string>DSFH IM Residency Calendar</string>
      <key>PayloadIdentifier</key>
      <string>com.dsfh.residency.subcal.${xmlEscape(token)}</string>
      <key>PayloadType</key>
      <string>com.apple.subscribedcalendar.account</string>
      <key>PayloadUUID</key>
      <string>${payloadUuid}</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
      <key>SubCalAccountDescription</key>
      <string>${xmlEscape(name)} \u2014 DSFH IM</string>
      <key>SubCalAccountHostName</key>
      <string>${xmlEscape(host)}</string>
      <key>SubCalAccountPath</key>
      <string>${xmlEscape(path)}</string>
      <key>SubCalAccountPort</key>
      <integer>443</integer>
      <key>SubCalAccountUseSSL</key>
      <true/>
    </dict>
  </array>
  <key>PayloadDescription</key>
  <string>Adds your live DSFH IM Residency calendar. Events update automatically \u2014 no manual steps.</string>
  <key>PayloadDisplayName</key>
  <string>DSFH IM Residency Calendar</string>
  <key>PayloadIdentifier</key>
  <string>com.dsfh.residency.calendarprofile.${xmlEscape(token)}</string>
  <key>PayloadOrganization</key>
  <string>DSFH Internal Medicine Residency</string>
  <key>PayloadRemovalDisallowed</key>
  <false/>
  <key>PayloadType</key>
  <string>Configuration</string>
  <key>PayloadUUID</key>
  <string>${profileUuid}</string>
  <key>PayloadVersion</key>
  <integer>1</integer>
</dict>
</plist>
`;
    return new Response(plist, {
      headers: {
        ...CORS_HEADERS,
        "Content-Type": "application/x-apple-aspen-config",
        "Content-Disposition": 'attachment; filename="dsfh-calendar.mobileconfig"',
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
    });
  }

  const _p = profile.calendar_prefs ?? {};
  // Resolve prefs — support both new keys and old single-key format for backward compat
  const prefs = {
    rota:       _p.rota       !== undefined ? _p.rota       : true,
    oncall:     _p.oncall     !== undefined ? _p.oncall     : true,
    mm_mine:    _p.mm_mine    !== undefined ? _p.mm_mine    : (_p.mm !== undefined ? _p.mm : true),
    mm_all:     _p.mm_all     !== undefined ? _p.mm_all     : false,
    teach_mine: _p.teach_mine !== undefined ? _p.teach_mine : false,
    teach_all:  _p.teach_all  !== undefined ? _p.teach_all  : (_p.teach !== undefined ? _p.teach : false),
    deadlines:  _p.deadlines  !== undefined ? _p.deadlines  : true,
  };
  // For "my teaching only" — match presenter_label against display name (no resident_id in teaching_sessions)
  const myDisplayName = (profile.display_name ?? "").replace(/^Dr\.?\s*/i, "").trim().toLowerCase();
  const resId = profile.resident_id ?? null;
  const ay = currentAcademicYear();
  const calName = icsEscape(
    ((profile.display_name || "Resident").replace(/^Dr\.?\s*/i, "")) +
    " — DSFH IM " + ay + "/" + String(ay + 1).slice(-2)
  );

  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//DSFH IM Residency//Live Calendar Feed//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    fold("X-WR-CALNAME:" + calName),
    "X-WR-TIMEZONE:Asia/Riyadh",
    "X-PUBLISHED-TTL:PT1H",
    "REFRESH-INTERVAL;VALUE=DURATION:PT1H",
  ];

  const push = (...args: string[]) => lines.push(...args);

  // ── 1. Rotation blocks ─────────────────────────────────────────────────────
  if (prefs.rota && resId) {
    const { data: rots } = await sb
      .from("rotations")
      .select("block_number, rotation_name")
      .eq("resident_id", resId)
      .eq("academic_year", ay);

    (rots ?? []).forEach((r: { block_number: number; rotation_name: string }) => {
      const start = blockStartDate(r.block_number, ay);
      const end = new Date(start.getTime() + 28 * 86400000);
      push(
        "BEGIN:VEVENT",
        fold("SUMMARY:B" + r.block_number + " \u2013 " + icsEscape(r.rotation_name)),
        "DTSTART;VALUE=DATE:" + icsDate(start),
        "DTEND;VALUE=DATE:" + icsDate(end),
        fold("DESCRIPTION:Block " + r.block_number + " \u2022 " + icsEscape(r.rotation_name) + " \u2022 DSFH IM"),
        "CATEGORIES:Rotation",
        fold("UID:dsfh-rot-" + resId + "-b" + r.block_number + "-" + ay + "@dsfh.local"),
        "END:VEVENT",
      );
    });
  }

  // ── 2. On-Call duties ──────────────────────────────────────────────────────
  if (prefs.oncall && resId) {
    const { data: ocs } = await sb
      .from("oncall_schedule")
      .select("id, schedule_date, slot_key, is_extra")
      .eq("resident_id", resId)
      .order("schedule_date");

    (ocs ?? []).forEach((e: { id: string; schedule_date: string; slot_key: string; is_extra: boolean }) => {
      const lbl = SLOT_LABELS[e.slot_key] ?? e.slot_key;
      const [sh, eh] = slotTimes(e.slot_key, e.schedule_date);
      const ds = e.schedule_date.replace(/-/g, "");
      push(
        "BEGIN:VEVENT",
        "UID:dsfh-oncall-" + e.id + "@dsfh.local",
        fold("SUMMARY:\uD83C\uDFE5 On-Call: " + icsEscape(lbl) + (e.is_extra ? " \u26A0 Extra Penalty" : "")),
        "DTSTART;TZID=Asia/Riyadh:" + ds + "T" + sh,
        "DTEND;TZID=Asia/Riyadh:" + ds + "T" + eh,
        fold("DESCRIPTION:DSFH IM On-Call \u2013 " + icsEscape(lbl) + (e.is_extra ? "\\nExtra penalty shift" : "")),
        "CATEGORIES:On-Call",
        "END:VEVENT",
      );
    });
  }

  // ── 3. Morning Meeting sessions ────────────────────────────────────────────
  if (prefs.mm_mine || prefs.mm_all) {
    const { data: mms } = await sb
      .from("mm_sessions")
      .select("id, block_number, session_date, topic, presenter_resident_id, moderator_resident_id")
      .order("session_date");

    (mms ?? []).forEach((s: {
      id: string; block_number: number; session_date: string;
      topic: string; presenter_resident_id: number | null; moderator_resident_id: number | null;
    }) => {
      const isPresenter = resId && s.presenter_resident_id == resId;
      const isModerator = resId && s.moderator_resident_id == resId;
      // mm_mine only: skip sessions not assigned to me (only filter if user has a resident record)
      if (!prefs.mm_all && prefs.mm_mine && resId && !isPresenter && !isModerator) return;
      let role = "";
      if (isPresenter) role = " \uD83C\uDFA4 Presenter";
      else if (isModerator) role = " \uD83C\uDF99 Moderator";
      const ds = s.session_date.replace(/-/g, "");
      push(
        "BEGIN:VEVENT",
        "UID:dsfh-mm-" + s.id + "@dsfh.local",
        fold("SUMMARY:\u2600\uFE0F Morning Meeting" + role + (s.topic ? ": " + icsEscape(s.topic) : "")),
        "DTSTART;TZID=Asia/Riyadh:" + ds + "T080000",
        "DTEND;TZID=Asia/Riyadh:" + ds + "T090000",
        fold("DESCRIPTION:DSFH IM Morning Meeting \u2013 Block " + s.block_number + (role ? "\\nYour role: " + role.trim() : "")),
        "CATEGORIES:Morning Meeting",
        "END:VEVENT",
      );
    });
  }

  // ── 4. Teaching sessions ───────────────────────────────────────────────────
  if (prefs.teach_mine || prefs.teach_all) {
    const { data: teaches } = await sb
      .from("teaching_sessions")
      .select("id, block_number, session_date, topic, presenter_label")
      .order("session_date");

    (teaches ?? []).forEach((s: {
      id: string; block_number: number; session_date: string;
      topic: string; presenter_label: string;
    }) => {
      // teach_mine only: filter by name match (no resident_id in teaching_sessions table)
      if (!prefs.teach_all && prefs.teach_mine) {
        const lbl = (s.presenter_label ?? "").toLowerCase();
        if (!myDisplayName || !lbl.includes(myDisplayName.split(" ")[0])) return;
      }
      const ds = s.session_date.replace(/-/g, "");
      push(
        "BEGIN:VEVENT",
        "UID:dsfh-teach-" + s.id + "@dsfh.local",
        fold("SUMMARY:\uD83D\uDCDA Teaching: " + icsEscape(s.topic ?? "Teaching Session")),
        "DTSTART;TZID=Asia/Riyadh:" + ds + "T130000",
        "DTEND;TZID=Asia/Riyadh:" + ds + "T140000",
        fold("DESCRIPTION:DSFH IM Teaching \u2013 " + icsEscape(s.presenter_label ?? "") + " \u2013 Block " + s.block_number),
        "CATEGORIES:Teaching",
        "END:VEVENT",
      );
    });
  }

  // ── 5. Deadlines & Announcements ───────────────────────────────────────────
  if (prefs.deadlines) {
    const { data: anns } = await sb
      .from("announcements")
      .select("id, title, description, deadline_date, category, target_all, target_level, target_resident_id")
      .eq("academic_year", ay)
      .not("deadline_date", "is", null);

    let resLevel: string | null = null;
    if (resId) {
      const { data: resRow } = await sb
        .from("residents")
        .select("level")
        .eq("id", resId)
        .single();
      resLevel = resRow?.level ?? null;
    }

    (anns ?? []).forEach((a: {
      id: string; title: string; description: string; deadline_date: string;
      category: string; target_all: boolean; target_level: string | null; target_resident_id: number | null;
    }) => {
      const forMe =
        a.target_all ||
        (resLevel && a.target_level === resLevel) ||
        (resId && a.target_resident_id == resId);
      if (!forMe) return;
      const icon = ANN_ICON[a.category] ?? "📌";
      const ds = a.deadline_date.replace(/-/g, "");
      push(
        "BEGIN:VEVENT",
        "UID:dsfh-ann-" + a.id + "@dsfh.local",
        fold("SUMMARY:" + icsEscape(icon + " " + a.title + " \u2014 DUE")),
        "DTSTART;VALUE=DATE:" + ds,
        "DTEND;VALUE=DATE:" + ds,
        fold("DESCRIPTION:" + icsEscape((a.description ?? "") + " \u2022 DSFH IM Residency")),
        "CATEGORIES:Deadline",
        "END:VEVENT",
      );
    });

    // Leave Plan submission deadline — mirrors LP_DEADLINE in SFH_Residency_Portal.html
    // (hardcoded client-side, not stored in a table; keep this date in sync with it).
    if (resId) {
      push(
        "BEGIN:VEVENT",
        "UID:dsfh-lp-deadline-" + ay + "@dsfh.local",
        "SUMMARY:\u23F0 Leave Plan Submission \u2014 DUE",
        "DTSTART;VALUE=DATE:20260718",
        "DTEND;VALUE=DATE:20260718",
        fold("DESCRIPTION:" + icsEscape("Submit or finalize your leave plan for AY " + ay + "/" + String(ay + 1).slice(-2) + " \u2022 DSFH IM Residency")),
        "CATEGORIES:Deadline",
        "END:VEVENT",
      );
    }

    // GIM rotation preference submission deadline — DB-backed, only if open with a deadline set
    if (resId) {
      const { data: gimStatus } = await sb
        .from("gim_rota_status")
        .select("is_open, deadline")
        .eq("academic_year", ay)
        .maybeSingle();
      if (gimStatus?.is_open && gimStatus.deadline) {
        const ds = String(gimStatus.deadline).slice(0, 10).replace(/-/g, "");
        push(
          "BEGIN:VEVENT",
          "UID:dsfh-gim-deadline-" + ay + "@dsfh.local",
          "SUMMARY:\u23F0 GIM Rotation Preferences \u2014 DUE",
          "DTSTART;VALUE=DATE:" + ds,
          "DTEND;VALUE=DATE:" + ds,
          fold("DESCRIPTION:" + icsEscape("Submit your GIM rotation block preferences for AY " + ay + "/" + String(ay + 1).slice(-2) + " \u2022 DSFH IM Residency")),
          "CATEGORIES:Deadline",
          "END:VEVENT",
        );
      }
    }
  }

  lines.push("END:VCALENDAR");

  return new Response(lines.join("\r\n"), {
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "text/calendar; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
});
